#!/usr/bin/env bash
# Setting custom http to be X-Served-By as hostname
sudo apt-get -y update
sudo apt-get -y install nginx
sed ufw allow 'Nginx HTTP'
sudo sed -i "46i\add_header X-Served-By $HOSTNAME ;" /etc/nginx/sites-available/default
sudo service nginx restart
